2024-10-27 16:39:28,621 - __main__ - INFO - Starting Eater.com scraping...
2024-10-27 16:39:28,621 - __main__ - INFO - Initializing Eater.com scraper...
2024-10-27 16:40:02,621 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019240898350>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91b05e548d5a367593ee4228d6047475
2024-10-27 16:40:06,659 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019240898230>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91b05e548d5a367593ee4228d6047475
2024-10-27 16:40:10,703 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019240898590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91b05e548d5a367593ee4228d6047475
2024-10-27 16:41:08,964 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019240AB5820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c0333b8349a8169e6ae3c9be08f1b226
2024-10-27 16:42:30,843 - __main__ - INFO - Starting Eater.com scraping...
2024-10-27 16:42:30,843 - __main__ - INFO - Initializing Eater.com scraper...
2024-10-27 16:43:02,696 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BE6CB8F8F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2fb979316e8f4a4c9a3af801142ed66c
2024-10-27 16:47:44,240 - __main__ - INFO - Starting Eater.com scraping...
2024-10-27 16:47:44,240 - __main__ - INFO - Initializing Eater.com scraper...
2024-10-27 16:51:32,395 - __main__ - INFO - Starting Eater.com scraping...
2024-10-27 16:51:32,395 - __main__ - INFO - Initializing Eater.com scraper...
2024-10-27 17:04:41,543 - __main__ - INFO - Cleaning restaurant data...
2024-10-27 17:04:41,868 - __main__ - INFO - Initializing Google Maps data fetcher...
2024-10-27 17:04:41,874 - __main__ - ERROR - Error in main process: [Errno 2] No such file or directory: 's:\\restaurant-data-pipeline\\src\\data\\processed\\cleaned_restaurants_enhanced.csv'
2024-10-27 17:11:14,935 - __main__ - INFO - Starting Eater.com scraping...
2024-10-27 17:11:14,935 - __main__ - INFO - Initializing Eater.com scraper...
2024-10-27 17:24:13,209 - __main__ - INFO - Cleaning restaurant data...
2024-10-27 17:24:13,538 - __main__ - INFO - Initializing Google Maps data fetcher...
2024-10-27 17:24:13,554 - __main__ - ERROR - Error in main process: name 'logger' is not defined
2024-10-28 09:41:22,669 - src.database.db_operations - INFO - Connected to database at s:\restaurant-data-pipeline\src\data\database\restaurants.db
2024-10-28 09:41:22,675 - src.database.db_operations - INFO - Database connection closed
